---

- name: Install bluetooth libraries and tools
  pacman:
    name: [ "pulseaudio-bluetooth", "bluez", "bluez-libs", "bluez-utils", "bluez-firmware", "blueman" ]
    state: present
  notify:
    - restart pulse as user

- name: Do not auto power on the bluetooth device
  command: gsettings set org.blueman.plugins.powermanager auto-power-on false
  become: yes
  become_user: "{{ system.user.name }}"

- name: Unblock the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: no
    state: stopped
  when: not system.bluetooth.disabled

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: not system.bluetooth.disabled

- name: Disable and stop the bluetooth service
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: system.bluetooth.disabled

- name: Block the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: yes
    state: started
  when: system.bluetooth.disabled
