---
- name: Install gnupg
  pacman:
    name: gnupg
    state: present

- name: Enable gpg-agent.socket
  systemd:
    name: gpg-agent.socket
    user: yes
    enabled: yes
    state: started
  become: yes
  become_user: "{{ system.user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ system.user.uid }}"
  when: config.gnupg.enable_agent

- name: Enable dirmngr.socket
  systemd:
    name: dirmngr.socket
    user: yes
    enabled: yes
    state: started
  become: yes
  become_user: "{{ system.user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ system.user.uid }}"
  when: config.gnupg.enable_agent

- name: Enable gpg-agent-ssh.socket
  systemd:
    name: gpg-agent-ssh.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ system.user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ system.user.uid }}"
  when: config.gnupg.enable_agent and config.gnupg.emulate_ssh
