---

- name: Enable pacman colourised output and verbose package lists
  replace:
    path: "/etc/pacman.conf"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    -
      regexp: "^#Color$"
      replace: "Color"
    -
      regexp: "^#CheckSpace$"
      replace: "CheckSpace"
    -
      regexp: "^#VerbosePkgLists$"
      replace: "VerbosePkgLists"
