---

- name: Create user group
  group:
    name: "{{ system.user.group }}"
    state: present
  tags:
    - user

- name: Create user and assign to group
  user:
    name: "{{ system.user.name }}"
    group: "{{ system.user.group }}"
    password: "{{ user_password|password_hash('sha512') }}"
    shell: "{{ system.user.shell }}"
    update_password: on_create
    uid: "{{ system.user.uid }}"
    groups: uucp
    append: yes
  tags:
    - user

- name: Create user log dir
  file:
    path: "/home/{{ system.user.name }}/{{ system.logs.users.dir }}"
    state: directory
    owner: "{{ system.user.name }}"
    group: "{{ system.user.group }}"
  when: system.logs.users | length > 0
  tags:
    - user

- name: Create logrotate.d folder
  file:
    path: /etc/logrotate.d
    state: directory
  when: system.logs.users | length > 0
  tags:
    - user

- name: Push logrotate config for user logs
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/user
  when: system.logs.users | length > 0
  tags:
    - user

- name: Create user socket directory
  file:
    path: "/run/user/{{ system.user.uid }}"
    state: directory
    owner: "{{ system.user.name }}"
    group: "{{ system.user.group }}"
    mode: 0700
  tags:
    - user

- name: Start user systemd instance
  service:
    name: "user@{{ system.user.uid }}"
    state: started
  notify: "stop systemd per-user instance"
  tags:
    - user
